build:
    environment:
        php:
            version: 8.3.3
        postgresql: false
        redis: false
        rabbitmq: false
    nodes:
        tests:
            cache:
                directories:
                    - vendor/
            dependencies:
                override:
                    - wget https://www.phing.info/get/phing-latest.phar && mv phing-latest.phar phing && chmod +x phing
                    - composer update --prefer-dist --no-progress --no-suggest --no-interaction
            tests:
                override:
                    -
                        command: ./vendor/bin/phpcs . --extensions=php,phpt --report=checkstyle --report-file=codesniffer.cs --standard=vendor/nexendrie/code-quality/phpcs.xml
                        analysis:
                            file: codesniffer.cs
                            format: 'general-checkstyle'
                    -
                        command: ./phing ci-coverage
                        coverage:
                            file: coverage.xml
                            format: php-clover
